name: Deploy to IBM Cloud
description: Deploy to IBM Cloud
inputs:
  cloud-api-key:
    description: 'IBM Cloud API key'
    required: true
  cf-org:
    description: 'Name of organization to be targeted'
    required: true
  cf-space:
    description: 'Name of space to be targeted'
    required: true
  cf-group:
    description: 'Resource Group Name or ID'
    required: false
  cf-region:
    description: 'Name of region, such as "us-south" or "eu-gb"'
    required: false
  cf-api:
    description: 'Cloud Foundry API endpoint'
    required: false
  cf-app:
    description: 'Cloud Foundry application name'
    required: true
  cf-manifest:
    description: 'Cloud Foundry manifest file'
    required: false
  deploy-dir:
    description: 'The root directory to deploy'
    required: false
runs:
  using: node12
  main: dist/index.js
  post: dist/logout.js
